# Generated by Django 3.0 on 2022-04-21 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='lettings_address',
        ),
        migrations.AlterModelTable(
            name='letting',
            table='lettings_letting',
        ),
    ]
