# Generated by Django 3.0 on 2022-04-25 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lettings', '0002_auto_20220421_1727'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='oc_lettings_address',
        ),
        migrations.AlterModelTable(
            name='letting',
            table='oc_lettings_letting',
        ),
    ]
