# Generated by Django 3.0 on 2022-04-21 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles_profile',
        ),
    ]
