# Generated by Django 3.0 on 2022-04-25 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0002_auto_20220421_1727'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='oc_lettings_site_profile',
        ),
    ]
