# Generated by Django 3.0 on 2022-04-25 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0003_auto_20220425_1949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
